/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as SignupImport } from './routes/signup'
import { Route as ResetPasswordImport } from './routes/reset-password'
import { Route as RecoverPasswordImport } from './routes/recover-password'
import { Route as LoginImport } from './routes/login'
import { Route as HomeImport } from './routes/home'
import { Route as ComparisionsImport } from './routes/comparisions'
import { Route as IndexImport } from './routes/index'
import { Route as HomeLayoutImport } from './routes/home/_layout'
import { Route as HomeLayoutIndexImport } from './routes/home/_layout/index'
import { Route as HomeLayoutSettingsImport } from './routes/home/_layout/settings'
import { Route as HomeLayoutItemsImport } from './routes/home/_layout/items'
import { Route as HomeLayoutAdminImport } from './routes/home/_layout/admin'

// Create/Update Routes

const SignupRoute = SignupImport.update({
  path: '/signup',
  getParentRoute: () => rootRoute,
} as any)

const ResetPasswordRoute = ResetPasswordImport.update({
  path: '/reset-password',
  getParentRoute: () => rootRoute,
} as any)

const RecoverPasswordRoute = RecoverPasswordImport.update({
  path: '/recover-password',
  getParentRoute: () => rootRoute,
} as any)

const LoginRoute = LoginImport.update({
  path: '/login',
  getParentRoute: () => rootRoute,
} as any)

const HomeRoute = HomeImport.update({
  path: '/home',
  getParentRoute: () => rootRoute,
} as any)

const ComparisionsRoute = ComparisionsImport.update({
  path: '/comparisions',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const HomeLayoutRoute = HomeLayoutImport.update({
  id: '/_layout',
  getParentRoute: () => HomeRoute,
} as any)

const HomeLayoutIndexRoute = HomeLayoutIndexImport.update({
  path: '/',
  getParentRoute: () => HomeLayoutRoute,
} as any)

const HomeLayoutSettingsRoute = HomeLayoutSettingsImport.update({
  path: '/settings',
  getParentRoute: () => HomeLayoutRoute,
} as any)

const HomeLayoutItemsRoute = HomeLayoutItemsImport.update({
  path: '/items',
  getParentRoute: () => HomeLayoutRoute,
} as any)

const HomeLayoutAdminRoute = HomeLayoutAdminImport.update({
  path: '/admin',
  getParentRoute: () => HomeLayoutRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/comparisions': {
      preLoaderRoute: typeof ComparisionsImport
      parentRoute: typeof rootRoute
    }
    '/home': {
      preLoaderRoute: typeof HomeImport
      parentRoute: typeof rootRoute
    }
    '/login': {
      preLoaderRoute: typeof LoginImport
      parentRoute: typeof rootRoute
    }
    '/recover-password': {
      preLoaderRoute: typeof RecoverPasswordImport
      parentRoute: typeof rootRoute
    }
    '/reset-password': {
      preLoaderRoute: typeof ResetPasswordImport
      parentRoute: typeof rootRoute
    }
    '/signup': {
      preLoaderRoute: typeof SignupImport
      parentRoute: typeof rootRoute
    }
    '/home/_layout': {
      preLoaderRoute: typeof HomeLayoutImport
      parentRoute: typeof HomeImport
    }
    '/home/_layout/admin': {
      preLoaderRoute: typeof HomeLayoutAdminImport
      parentRoute: typeof HomeLayoutImport
    }
    '/home/_layout/items': {
      preLoaderRoute: typeof HomeLayoutItemsImport
      parentRoute: typeof HomeLayoutImport
    }
    '/home/_layout/settings': {
      preLoaderRoute: typeof HomeLayoutSettingsImport
      parentRoute: typeof HomeLayoutImport
    }
    '/home/_layout/': {
      preLoaderRoute: typeof HomeLayoutIndexImport
      parentRoute: typeof HomeLayoutImport
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  IndexRoute,
  ComparisionsRoute,
  HomeRoute.addChildren([
    HomeLayoutRoute.addChildren([
      HomeLayoutAdminRoute,
      HomeLayoutItemsRoute,
      HomeLayoutSettingsRoute,
      HomeLayoutIndexRoute,
    ]),
  ]),
  LoginRoute,
  RecoverPasswordRoute,
  ResetPasswordRoute,
  SignupRoute,
])

/* prettier-ignore-end */
